version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: docker
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: hospitaldb
      DB_USER: hospitaluser
      DB_PASSWORD: hospitaluser1234
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: hospitaldb
      POSTGRES_USER: hospitaluser
      POSTGRES_PASSWORD: hospitaluser1234
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
